### ISSUE TITLE
Upgrade PHPUnit version used for Unit Tests

### ISSUE THREAD

**Issue by raaaahman** [WordPress/wp-feature-notifications#12]
https://github.com/WordPress/wp-notify/blob/af086175c661586f691947886a519f8b550a6f5d/composer.json#L6

Because WordPress still needs to support PHP 5.6 environments, the maximum version we could use is 7.5.*.

The upgrade from 3 to 7 is expected to cause several errors in the tests code.

**Comment by szepeviktor** [comment]
You can simplify testing with https://github.com/Automattic/wordbless

**Comment by erikyo** [comment]
closing because outdated, this is something that was recently updated by #123
