### ISSUE TITLE
Create a shareable environment

### ISSUE THREAD

**Issue by raaaahman** [WordPress/wp-feature-notifications#14]
Because the project will be developed on several contributors' computers, we should create a shareable environment in order to prevent the "works on my machine" syndrome.

This means either sharing a **virtual machine** or a set of **containers**.

Two projects have been set up to facilitate this work in a WordPress environment, [Varying Vagrant Vagrants](https://varyingvagrantvagrants.org/) (virtualization) and  [Lando (WordPress recipe)](https://docs.lando.dev/config/wordpress.html#getting-started).

Also, we may set up a Docker-Composer environment based on [WordPress-Develop environment](https://github.com/WordPress/wordpress-develop#development-environment-commands).

Going further, using either of this solutions will provide us the ability to quickly switch environments (PHP version, Apache or NGINX, Linux distribution, etc.) to make sure the project can run on the variety of server configuration that powers the web.

**Comment by Mahjouba91** [comment]
Docker would be a better solution IMO

**Comment by jonathanbossenger** [comment]
wp-env seems to be a solution for this problem https://make.wordpress.org/core/2020/03/03/wp-env-simple-local-environments-for-wordpress/

**Comment by jonathanbossenger** [comment]
I'm going to test wp-env this week, will report back my findings before the next office hours.

**Comment by jonathanbossenger** [comment]
Sadly I did not get to this as planned, will schedule it for the coming week.

**Comment by erikyo** [comment]
later we added wp-env. close because outdated
