### ISSUE TITLE
Storybook as repo documentation

### ISSUE THREAD

**Issue by erikyo** [WordPress/wp-feature-notifications#147]
## What problem does this address?
Actually we haven't a (easy to reach) user documentation

## What is your proposed solution?
Using storybook we can create a little nicer documentation than the traditional one, and also we can show the components of the project and play with them. Using `build-storybook -o docs/`, should published and shown in the right panel of the Github repo home page

Here an example:
[feature-notifications Storybook](https://dev.codekraft.it/navtest/wp-notify/?path=/story/feature-notifications-introduction--page)

**Comment by Sephsekla** [comment]
When this is merged I'll look at disabling the repo wiki - a lot of this is out of date anyway and we don't want to be maintaining duplicate docs.
