### ISSUE TITLE
Add the ability to expand the Notification Hub

### ISSUE THREAD

**Issue by johnhooks** [WordPress/wp-feature-notifications#186]
## What problem does this address?

The Notification Hub is rendered at a fixed width and some of the notification messages feel tight, which could even worse in other languages.

## What is your proposed solution?

Adding the ability to drag the sidebar edge and widen the Hub area would provide the user more control over how they view their notifications.

**Comment by erikyo** [comment]
Currently Gutenberg is using this [plugin](https://github.com/bokuweb/re-resizable#props) to resize images, we could investigate a possible use since it isn't an additional dependency.
