### ISSUE TITLE
Create a GitHub action to build scripts and styles when a new release is tagged

### ISSUE THREAD

**Issue by Sephsekla** [WordPress/wp-feature-notifications#187]
## What problem does this address?

Currently, scripts and styles are manually built, and committed to the repo. This is not ideal.

## What is your proposed solution?

@JasonTheAdams has kindly provided a good starting point at https://github.com/impress-org/givewp-github-actions/blob/59fcb8b536bd4955c6fa7319fac7f0c0558408d4/.github/workflows/givewp-release.yml#L129-L137. This will need updating for our workflow.

**Comment by Sephsekla** [comment]
The action used in GiveWP's script has been archived, so I'm investigating the suggested replacement: https://github.com/softprops/action-gh-release

**Comment by JasonTheAdams** [comment]
Yeah, it still works, but we have it on our list to replace it in the next couple weeks.
