### ISSUE TITLE
Change rest-api namespace to `wp-notifications/v1`

### ISSUE THREAD

**Issue by johnhooks** [WordPress/wp-feature-notifications#194]
## What problem does this address?

The plugin should not use the core `wp/v2` namespace 

## What is your proposed solution?

@TimothyBJacobs suggested `wp-notifications/v1` in #179, which sounds good.

Another thought is to stick with the "Notify" name and do `wp-notify/v1`, this is shorter, and if this does merge into core, the "wp-notify" namespace/prefix used everywhere would simply become "wp".

**Comment by Sephsekla** [comment]
This is good call, and I think having a version in there is smart.

I'd prefer to go with wp-notifications over wp-notify, we switched over for a reason and we should try and be as consistent as we can.

**Comment by johnhooks** [comment]
@Sephsekla with this change, `/wp-json/wp-notifications/v1/notifications` seems like an odd endpoint. How do you feel about `/wp-json/wp-notifications/v1/messages`? In consideration that it would be part of:

```
/wp-json/wp-notifications/v1/messages
/wp-json/wp-notifications/v1/channels
/wp-json/wp-notifications/v1/subscriptions
```

Also the class name with namespace would be more descriptive. Example: 

`WP/Notifications/Message` and `WP/Notifications/Message_Controller`

Rather than:

`WP/Notifications/Notification` and `WP/Notifications/Notification_Controller`

Just thoughts. I'm leaving it as `/wp-json/wp-notifications/v1/notifications` unless I hear otherwise.
