### ISSUE TITLE
Create naming convention

### ISSUE THREAD

**Issue by johnhooks** [WordPress/wp-feature-notifications#197]
## What problem does this address?

Reduce developer confusion.

## What is your proposed solution?

We should decided on a naming convention, document it, and clean up all the old names in the project.

I do not care what the naming convention is, but I began work on new features, and the naming issues in the project make me very uncertain how I should name things. It's also very odd when they have to be used together.

This is related to #4, #190 and #194.

## Convention Todo List

- [x] Plugn name

  - [x] `WP Feature Notifications`
  - ~[ ] `WP Notifications`~
 
- [x] Package name

  - ~[ ] `WP_Feature_Notifications`~
  - ~[ ] `WP_Notifications`~
  - [x] `wordpress/wp-feature-notifications` in [class-notification-controller.php](https://github.com/WordPress/wp-feature-notifications/blob/c8714bda9e65512730c17d431d2dc96f051cd1fd/includes/restapi/class-notification-controller.php#L5)
 
- [x] Text Domain

  The text domain must match the slug of the plugin, see [Text Domain](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains).

  - [x] `wp-feature-notifications`
  - ~[ ] `wp-notifications`~

- [x] Namespace

  The rest controller uses the namespace `WP\Notifications`

  - [x] Should we convert the whole project?
  - ~[ ] Should we use a PSR-4 compliant file structure?~
 
- [x] Class and Interface

  - [x] If using namespaces, should all the `WP_Notify` prefixes be removed?

- [x] Class and Interface files
  
  The rest controller uses the file name `class-*`, no prefix
  
  The rest use `class-wp-notify-*`

  - [x] If converting to namespaces, should all the files be renamed to remove the `wp-notify` prefix?

- [x] Global define variables
  
  The current prefix is `WP_NOTIFICATION_CENTER_*`, found in `wp-feature-notifications.php`

  - [x] Should we use `WP_FEATURE_NOTIFICATIONS_*`
  - ~[ ] Use namespaced const variables~

@Sephsekla, @erikyo pointed out this doesn't consider updates in the JavaScript or CSS.

- [x] CSS Custom Properties

   I suggest using shorter a condensed namespace, the chances are very low that there will be a conflict.
  - [x] Should we use `wp-notifications-*` for class names?
  - [x] Should we use `--wp-notifications-*` for custom properties?

**Comment by johnhooks** [comment]
@Sephsekla does it let you check off the boxes? If so, feel free to just check off everything that aligns with how you envision this working.

**Comment by Sephsekla** [comment]
This is honestly a tricky one, and it's seen a fair amount of discussion already. Any deviation from https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#naming-conventions is going to add additional friction to getting this merged into WP Core, however a stated goal of the project is to push modern best practice.

I'm very much in favour of going with namespaces rather than prefixes, but I don't know how far to go with filenames for PSR-4.

Let's discuss it in this week's meeting.

**Comment by johnhooks** [comment]
@Sephsekla I don't have a horse in the race of which we go with. I would just like it documented and decisions need to be made how to name things, and then get the whole repo up to date.

**Comment by johnhooks** [comment]
@Sephsekla should this be in the CONTRIBUTING.md or in a separate document?

**Comment by johnhooks** [comment]
@Sephsekla, @erikyo pointed out this doesn't consider updates in the JavaScript or CSS.

- [ ] How should css class names and variables be name spaced?
  - [ ] Should we use `wp-feature-notifications-*` for class names?
  - [ ] Should we use `--wp-feature-notifications-*` for custom properties?

Are there any other considerations?

**Comment by johnhooks** [comment]
The final fix was merged in #292
