### ISSUE TITLE
Design for a notifications archive

### ISSUE THREAD

**Issue by hedgefield** [WordPress/wp-feature-notifications#25]
Splitting this out from #1, this is the place to discuss the design for the notifications _archive_.

I saw mention of this in [the requirements document](https://docs.google.com/document/d/1SoIaFqXkXiVzq5mizbZQafMfL36bD0WKj8iwYM823MI/edit), a page that lists all the notifications chronologically. The usecase is not entirely clear to me, perhaps this could also be done by scrolling down the notifications admin menu, but then again having a dedicated page, perhaps with expanded actions of some kind, might be a nice idea. Not sure how it fits with [the settings page](https://github.com/WordPress/wp-notify/issues/24) yet.

I did a quick mockup for it here: https://www.figma.com/file/PIRT7PBfCYIxn4urohVInn/WP-Notify-design-v2-Tim?node-id=231%3A10

![archive](https://user-images.githubusercontent.com/6073772/99539508-9d988980-29ae-11eb-94ea-b46133edf045.png)

**Comment by raaaahman** [comment]
> The usecase is not entirely clear to me, perhaps this could also be done by scrolling down the notifications admin menu

:thinking: Indeed, I can't really remember the reason it has made it through the requirements...

**Comment by folletto** [comment]
Can you point out the specific bit of the requirements doc? I can find just:

> A hub that shows all notification-type messages chronologically.

But this refers to the dropdown itself.

**Comment by hedgefield** [comment]
Ah you are correct, I read it too fast and saw "an admin bar integration" and "a hub for chronological messages", but those of course refers to the same thing, the bell icon + the dropdown that appears when you click on it. Never mind! I think we can close this issue then.

**Comment by hedgefield** [comment]
Should we close this issue then?
