### ISSUE TITLE
Define the Icon / Image model

### ISSUE THREAD

**Issue by raaaahman** [WordPress/wp-feature-notifications#47]
If we look at the designs for On-Hub notifications, there is two uses for images in the notifications:

- One is the icon that represents the **sender** (see [this comment]((https://github.com/WordPress/wp-notify/issues/41#issuecomment-773525936 )) in the Sender model discussion)
- The other is an image related to the message of the notification

Maybe both the Sender model and the Notification model would depend on a third model: the Image model?

Here are the data it should contain:

- **source**: string. An URL or data URL (see details below)
- **alternative_text**: string. Description of the image for accessibility purpose.

On the front-end, the `<img>` tag should be able to handle all the use cases:

- An **external URL** will be resolved in a same way by its [src attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-src) whether the format of the image is PNG, JPEG or SVG.
- This `src` attribute can as well accept a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) to directly embed base64 encoded raster images or SVG inside the notification itself (saves an HTTP request, per notification!)

**Comment by danbilauca** [comment]
I'd also add a target url property where the users would be redirected after clicking on the Icon/Image. Now, I am not sure if the URL should open in the same tab or in a new one.

Should the URL be a property of the Sender parent model ? In case it is defined then the Image/Icon should be rendered in an anchor `<a/>` ?

**Comment by folletto** [comment]
The only interaction is at the notification level, not at image level. See the general data model on https://github.com/WordPress/wp-notify/issues/16#issuecomment-724608463

**Comment by danbilauca** [comment]
I've opened this PR #51 for Image Model

**Comment by raaaahman** [comment]
Solved in #51
