### ISSUE TITLE
Move the documentation from the develop branch to the wiki

### ISSUE THREAD

**Issue by raaaahman** [WordPress/wp-feature-notifications#62]
## Describe the issue

New contributors could use some pointers about:

- How to setup the development environment (info available here: https://github.com/WordPress/wp-notify/tree/develop/docs)
- How to name branches and onto which branches they should make their pull requests (the `develop` branch)

## Proposal

Write this information inside the wiki, so it is easily available for newcomers. An issue might be to keep this information updated as the tooling / workflows get refined.

Maybe information such as database schemas should remain in the branches, so if the schema needs to change, it will still be relevant in both branches before the merge is finally done. (Any tool might be subject to such change as well...)

**Comment by Sephsekla** [comment]
Closed in favour of current storybook-based wiki.
